### ISSUE TITLE
"zsh: illegal hardware instruction" with Mac M1

### ISSUE THREAD

**Issue by abauville** [styfenschaer/rocket-fft#1]
Hello,

Thanks for the package, it's exactly what I need. However, I'm running into this error:

```
zsh: illegal hardware instruction python main.py
```

My test code is pretty minimal:
```
# main.py
from numba import njit
import numpy as np

@njit
def jit_fft(x):
    return np.fft.fft(x)

a = np.array([2., 7, 1, 8, 2, 8, 1, 8])
jit_fft(a)
```

A quick look e.g. [here](https://stackoverflow.com/questions/65383338/zsh-illegal-hardware-instruction-python-when-installing-tensorflow-on-macbook) tells me it's probably related to something specific to the Mac M1 architecture.

===
I'm running on MacOS Monterey 12.4 on a MacBook Air (M1, 2020)
I'm using a fresh python=3.10 conda environment

Are you considering supporting these chips?
Thanks in advance

**Comment by styfenschaer** [comment]
Hi

Thanks for reporting this issue. 

Did you install it from PyPI or did you build the package yourself? If you got it from PyPI, I tend to say that the problem is caused by the vector instructions used by the PocketFFT library. 

Can you please try version 0.1.0? 
```
pip install rocket-fft==0.1.0
``` 
I changed the compiler flags from v0.1.0 to v0.1.2, which was probably a mistake.

If this solves the problem please report back to me. You work with v0.1.0, since the only real improvement from v0.1.0 to v0.1.2 is better performance for small transforms. I will then provide a new release so you can upgrade to the latest features.

**Comment by abauville** [comment]
Hi,

Yes,  I installed it from PyPI, and yes going back to v0.1.0 fixed the problem 🎉.
Thanks a lot for your quick response and for the awesome software
