### ISSUE TITLE
Linux arm64 builds

### ISSUE THREAD

**Issue by benhowes** [styfenschaer/rocket-fft#6]
Would you be open to adding a linux arm64 build to pypi? As far as I can see it should be possible via `cibuildwheel`.

In my usecase, it would be handy as I'm running linux docker containers on macos.

Many thanks for a great project!

**Comment by styfenschaer** [comment]
Hi @benhowes,

Thank you for your suggestion. I'm open to the idea of providing Linux ARM64 wheels, provided it's technically feasible. However, implementing this on GitHub runners might require some additional steps. If you already have a solution in mind, I welcome you to submit a pull request. Otherwise, I'll try to explore this soon.
